package me.tbsten.defaultargcapture

import com.google.auto.service.AutoService
import org.jetbrains.kotlin.compiler.plugin.AbstractCliOption
import org.jetbrains.kotlin.compiler.plugin.CommandLineProcessor

/**
 * Command-line processor for the defaultArgOf compiler plugin.
 *
 * Declares the plugin ID (`me.tbsten.defaultargcapture`) used by the Kotlin compiler
 * to match this plugin with its [registrar][DefaultArgOfPluginRegistrar].
 * Currently accepts no CLI options.
 *
 * ### How it works
 * The Kotlin compiler discovers this processor via `META-INF/services/` (generated by
 * `@AutoService`). When the plugin ID matches, the compiler loads the corresponding
 * [DefaultArgOfPluginRegistrar] to register FIR and IR extensions.
 *
 * ### Adding CLI options
 * To pass configuration from Gradle to the compiler plugin, add [AbstractCliOption]
 * entries to [pluginOptions] and handle them in [DefaultArgOfPluginRegistrar.registerExtensions].
 */
@AutoService(CommandLineProcessor::class)
class DefaultArgOfCommandLineProcessor : CommandLineProcessor {
    override val pluginId: String = "me.tbsten.defaultargcapture"
    override val pluginOptions: Collection<AbstractCliOption> = emptyList()
}
